# Project-wide Gradle settings for the Android project
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.util=ALL-UNNAMED
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true
googleServices.missing.passthrough=true
android.jdk.image.transform=false
kotlin.jvm.target.validation.mode=warning

