import React, { useMemo, useState } from 'react';
import { Activity, CalendarDays, CheckCircle2, HeartPulse, Inbox, NotebookPen } from 'lucide-react';
import { Appointment, DoseEvent, JournalEntry, QuickCapture, Task, TimelineEntry, VitalSign } from '../types';
import { buildLifeTimeline, LifeTimelineKind } from '../utils/lifeTimeline';

interface Props { timelineEntries: TimelineEntry[]; tasks: Task[]; captures: QuickCapture[]; journalEntries: JournalEntry[]; doseEvents: DoseEvent[]; vitalSigns: VitalSign[]; appointments: Appointment[]; }
const filters: Array<{ value: 'ALL' | LifeTimelineKind; label: string }> = [{ value: 'ALL', label: 'All' }, { value: 'WORK', label: 'Work' }, { value: 'HEALTH', label: 'Health' }, { value: 'REFLECTION', label: 'Reflection' }, { value: 'CAPTURE', label: 'Captures' }, { value: 'APPOINTMENT', label: 'Appointments' }];
const icons = { WORK: CheckCircle2, HEALTH: HeartPulse, REFLECTION: NotebookPen, CAPTURE: Inbox, APPOINTMENT: CalendarDays };

export const LifeTimeline: React.FC<Props> = (props) => {
  const [filter, setFilter] = useState<'ALL' | LifeTimelineKind>('ALL');
  const [limit, setLimit] = useState(12);
  const items = useMemo(() => buildLifeTimeline(props), [props.timelineEntries, props.tasks, props.captures, props.journalEntries, props.doseEvents, props.vitalSigns, props.appointments]);
  const filtered = filter === 'ALL' ? items : items.filter((item) => item.kind === filter);
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4 shadow-lg sm:p-5" aria-labelledby="life-timeline-title">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-indigo-300" /><h2 id="life-timeline-title" className="font-heading text-lg font-bold text-white">Your life timeline</h2></div><p className="mt-1 text-xs text-slate-400">One chronological record across work, health, captures, reflection, and appointments.</p></div><span className="text-xs text-slate-500">{filtered.length} records</span></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1" role="group" aria-label="Filter timeline">{filters.map((item) => <button key={item.value} type="button" onClick={() => { setFilter(item.value); setLimit(12); }} aria-pressed={filter === item.value} className={`shrink-0 rounded-full px-3 py-1.5 text-[11px] font-semibold ${filter === item.value ? 'bg-indigo-600 text-white' : 'border border-slate-700 bg-slate-950 text-slate-400 hover:text-white'}`}>{item.label}</button>)}</div>
    <div className="mt-4 space-y-1">{filtered.slice(0, limit).map((item, index) => { const Icon = icons[item.kind]; const date = new Date(item.timestampMillis); const showDate = index === 0 || new Date(filtered[index - 1].timestampMillis).toDateString() !== date.toDateString(); return <React.Fragment key={item.id}>{showDate && <p className="pb-1 pt-3 text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500 first:pt-0">{date.toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}</p>}<article className="flex gap-3 rounded-xl border border-transparent px-2 py-3 hover:border-slate-800 hover:bg-slate-950/50"><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-slate-700 bg-slate-950"><Icon className="h-4 w-4 text-indigo-300" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="truncate text-sm font-semibold text-slate-100">{item.title}</h3><time className="shrink-0 text-[10px] text-slate-500">{date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</time></div>{item.detail && <p className="mt-0.5 line-clamp-2 text-xs text-slate-400">{item.detail}</p>}<p className="mt-1 text-[10px] font-medium text-slate-600">Source: {item.source}</p></div></article></React.Fragment>; })}{filtered.length === 0 && <div className="rounded-xl border border-dashed border-slate-700 py-10 text-center text-sm text-slate-500">No records match this filter yet.</div>}</div>
    {filtered.length > limit && <button type="button" onClick={() => setLimit((value) => value + 20)} className="mt-4 w-full rounded-xl border border-slate-700 py-2.5 text-xs font-semibold text-slate-300 hover:border-indigo-500 hover:text-white">Show earlier activity</button>}
  </section>;
};
