import React, { useState } from 'react';
import { BarChart2, Book, BookOpen, CheckSquare, Clock, HeartPulse, Layers, Settings, Sparkles, Sun, UserRound, Zap } from 'lucide-react';
import { NavTab } from '../types';
interface Props { activeTab: NavTab; onSelectTab: (tab: NavTab) => void; onOpenCapture: () => void; }
const spaces = [
  { id: NavTab.TASKS, label: 'Tasks', detail: 'Commitments and priorities', icon: CheckSquare }, { id: NavTab.AI, label: 'Assistant', detail: 'Ask and act safely', icon: Sparkles },
  { id: NavTab.HEALTH, label: 'Health', detail: 'Medication and wellbeing', icon: HeartPulse }, { id: NavTab.JOURNAL, label: 'Journal', detail: 'Notes and reflections', icon: Book },
  { id: NavTab.LEARN, label: 'Learn', detail: 'Study and recall', icon: BookOpen }, { id: NavTab.PLUGINS, label: 'Tools', detail: 'Money and extensions', icon: Layers },
  { id: NavTab.SETTINGS, label: 'Settings', detail: 'Account and preferences', icon: Settings },
];
export const MobileBottomNav: React.FC<Props> = ({ activeTab, onSelectTab, onOpenCapture }) => {
  const [open, setOpen] = useState(false); const select = (tab: NavTab) => { setOpen(false); onSelectTab(tab); }; const spaceActive = spaces.some((item) => item.id === activeTab);
  const item = (active: boolean) => `flex min-h-[52px] flex-col items-center justify-center rounded-xl text-[9.5px] font-medium ${active ? 'text-indigo-200' : 'text-slate-400'}`; const pill = (active: boolean) => `flex h-6 w-11 items-center justify-center rounded-full ${active ? 'border border-indigo-500/50 bg-indigo-600/40' : ''}`;
  return <>{open && <div className="fixed inset-0 z-40 bg-slate-950/60 md:hidden" onClick={() => setOpen(false)} aria-hidden="true" />}<nav className="fixed bottom-0 left-0 right-0 z-50 border-t border-slate-800/80 bg-slate-950/95 pb-[env(safe-area-inset-bottom,8px)] shadow-2xl backdrop-blur-2xl md:hidden" aria-label="Primary navigation">
    {open && <div className="absolute bottom-full left-3 right-3 mb-2 rounded-2xl border border-slate-700 bg-slate-900 p-3 shadow-2xl"><div className="mb-2 px-1"><p className="text-xs font-bold text-white">Your spaces</p><p className="text-[10px] text-slate-400">Health, knowledge, tools, and preferences.</p></div><div className="grid grid-cols-2 gap-2">{spaces.map(({ id, label, detail, icon: Icon }) => <button key={id} type="button" onClick={() => select(id)} className={`flex items-center gap-2.5 rounded-xl border p-3 text-left ${activeTab === id ? 'border-indigo-500/60 bg-indigo-950/50' : 'border-slate-800 bg-slate-950/70'}`}><Icon className="h-4 w-4 shrink-0 text-indigo-300" /><span className="min-w-0"><span className="block text-xs font-semibold text-white">{label}</span><span className="block truncate text-[9px] text-slate-500">{detail}</span></span></button>)}</div></div>}
    <div className="grid grid-cols-5 px-1.5 py-1.5"><button type="button" onClick={() => select(NavTab.TODAY)} className={item(activeTab === NavTab.TODAY)} aria-current={activeTab === NavTab.TODAY ? 'page' : undefined}><span className={pill(activeTab === NavTab.TODAY)}><Sun className="h-4 w-4" /></span><span className="mt-0.5">Today</span></button><button type="button" onClick={() => select(NavTab.TIMELINE)} className={item(activeTab === NavTab.TIMELINE)} aria-current={activeTab === NavTab.TIMELINE ? 'page' : undefined}><span className={pill(activeTab === NavTab.TIMELINE)}><Clock className="h-4 w-4" /></span><span className="mt-0.5">Plan</span></button><button type="button" onClick={onOpenCapture} className={item(false)}><span className="flex h-9 w-12 -translate-y-1 items-center justify-center rounded-full bg-indigo-600 text-white shadow-lg shadow-indigo-950"><Zap className="h-4 w-4" /></span><span>Capture</span></button><button type="button" onClick={() => select(NavTab.INSIGHTS)} className={item(activeTab === NavTab.INSIGHTS)} aria-current={activeTab === NavTab.INSIGHTS ? 'page' : undefined}><span className={pill(activeTab === NavTab.INSIGHTS)}><BarChart2 className="h-4 w-4" /></span><span className="mt-0.5">Insights</span></button><button type="button" onClick={() => setOpen((value) => !value)} className={item(open || spaceActive)} aria-expanded={open}><span className={pill(open || spaceActive)}><UserRound className="h-4 w-4" /></span><span className="mt-0.5">You</span></button></div>
  </nav></>;
};
