import React, { useEffect, useState } from 'react';
import { Bell, Cpu, Search, Zap } from 'lucide-react';
import { getNotificationsHistory } from '../utils/notifications';

interface Props { onOpenSearch: () => void; onOpenNotifications?: () => void; onOpenCommandBar?: () => void; }
export const TopHeaderBar: React.FC<Props> = ({ onOpenSearch, onOpenNotifications, onOpenCommandBar }) => {
  const [unreadCount, setUnreadCount] = useState(0);
  useEffect(() => { const refresh = () => setUnreadCount(getNotificationsHistory().filter((item) => !item.read).length); refresh(); window.addEventListener('paios_notification_change', refresh); return () => window.removeEventListener('paios_notification_change', refresh); }, []);
  return <header className="sticky top-0 z-30 border-b border-slate-800/80 bg-slate-900/95 px-3 py-2 text-slate-100 shadow-sm backdrop-blur-md pt-[env(safe-area-inset-top,0px)] sm:px-4"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3">
    <div className="flex shrink-0 items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-tr from-indigo-600 via-indigo-500 to-cyan-400 text-white shadow-md shadow-indigo-500/20"><Cpu className="h-5 w-5" /></div><div className="hidden sm:block"><p className="font-heading text-sm font-extrabold tracking-wider text-white">PAIOS</p><p className="text-[9px] text-slate-500">Your daily cockpit</p></div></div>
    <div className="flex items-center gap-1.5 sm:gap-2">{onOpenCommandBar && <button type="button" onClick={onOpenCommandBar} className="flex min-h-[38px] items-center gap-1.5 rounded-xl border border-indigo-500/30 bg-indigo-600/20 px-2.5 py-1.5 text-xs font-medium text-indigo-200 hover:bg-indigo-600/30 hover:text-white" title="Open command bar (Ctrl+K)"><Zap className="h-3.5 w-3.5" /><span className="hidden sm:inline">Command</span><kbd className="hidden rounded border border-slate-700 bg-slate-950/60 px-1 font-mono text-[10px] text-slate-400 lg:inline">Ctrl K</kbd></button>}<button type="button" onClick={onOpenSearch} className="flex min-h-[38px] min-w-[38px] items-center justify-center rounded-xl border border-slate-700/60 bg-slate-800/90 p-2 text-slate-300 hover:text-white" title="Search" aria-label="Search"><Search className="h-4 w-4" /></button>{onOpenNotifications && <button type="button" onClick={onOpenNotifications} className="relative flex min-h-[38px] min-w-[38px] items-center justify-center rounded-xl border border-slate-700/60 bg-slate-800/90 p-2 text-slate-300 hover:text-white" title="Notification center" aria-label="Notification center"><Bell className="h-4 w-4" />{unreadCount > 0 && <span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-indigo-500 px-1 text-[9px] font-bold text-white">{unreadCount > 99 ? '99+' : unreadCount}</span>}</button>}</div>
  </div></header>;
};
